name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze (.NET Framework)
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\sonar-scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\sonar-scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\sonar-scanner

      - name: Download nuget.exe
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\nuget -ItemType Directory -Force | Out-Null
          Invoke-WebRequest -Uri "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile "${{ runner.temp }}\nuget\nuget.exe" -UseBasicParsing

      - name: Restore NuGet packages
        shell: powershell
        run: |
          $sln = (Get-ChildItem -Recurse -Filter "*.sln" | Select-Object -First 1).FullName
          if (-not $sln) { throw "No .sln file found" }
          & "${{ runner.temp }}\nuget\nuget.exe" restore "$sln"

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          $sln = (Get-ChildItem -Recurse -Filter "*.sln" | Select-Object -First 1).FullName
          if (-not $sln) { throw "No .sln file found" }

          ${{ runner.temp }}\sonar-scanner\dotnet-sonarscanner begin /k:"daviddierckx_AvansDevOps" /o:"daviddierckx-1" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          msbuild "$sln" /t:Rebuild /p:Configuration=Release /p:platform="Any CPU"
          ${{ runner.temp }}\sonar-scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"